# Generated by Django 5.1.4 on 2025-04-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MockExperianReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bureau_score",
                    models.IntegerField(help_text="The credit score of the user."),
                ),
                (
                    "score_band",
                    models.CharField(
                        help_text="The band of the credit score (e.g., low, medium, high).",
                        max_length=100,
                    ),
                ),
                (
                    "report_status",
                    models.CharField(
                        default="mocked",
                        help_text="The status of the report (e.g., mocked).",
                        max_length=50,
                    ),
                ),
                (
                    "total_accounts",
                    models.IntegerField(
                        help_text="The total number of credit accounts."
                    ),
                ),
                (
                    "active_accounts",
                    models.IntegerField(
                        help_text="The number of active credit accounts."
                    ),
                ),
                (
                    "overdue_accounts",
                    models.IntegerField(
                        help_text="The number of overdue credit accounts."
                    ),
                ),
                (
                    "dpd_max",
                    models.IntegerField(
                        help_text="The maximum number of Days Past Due (DPD) for credit accounts."
                    ),
                ),
                (
                    "credit_utilization_pct",
                    models.FloatField(
                        help_text="The percentage of credit utilization."
                    ),
                ),
                (
                    "emi_to_income_ratio",
                    models.FloatField(help_text="The ratio of EMI to income."),
                ),
                (
                    "tradelines",
                    models.JSONField(
                        blank=True,
                        help_text="The tradelines in the credit report.",
                        null=True,
                    ),
                ),
                (
                    "enquiries",
                    models.JSONField(
                        blank=True,
                        help_text="The enquiries in the credit report.",
                        null=True,
                    ),
                ),
                (
                    "mock_raw_report",
                    models.JSONField(
                        help_text="The raw mock API response for the credit report."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when this report was created.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockKYCRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        help_text="The PAN number of the user.", max_length=20
                    ),
                ),
                (
                    "pan_holder_name",
                    models.CharField(
                        help_text="The name on the PAN card.", max_length=255
                    ),
                ),
                (
                    "pan_verified",
                    models.BooleanField(
                        default=True, help_text="Indicates whether the PAN is verified."
                    ),
                ),
                (
                    "aadhaar_last_4",
                    models.CharField(
                        help_text="The last 4 digits of the Aadhaar number.",
                        max_length=4,
                    ),
                ),
                (
                    "aadhaar_verified",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the Aadhaar is verified.",
                    ),
                ),
                ("dob", models.DateField(help_text="The date of birth of the user.")),
                (
                    "kyc_type",
                    models.CharField(
                        default="full",
                        help_text="The type of KYC (e.g., full or simplified).",
                        max_length=50,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        default="verified",
                        help_text="The status of the KYC verification.",
                        max_length=50,
                    ),
                ),
                (
                    "verification_source",
                    models.CharField(
                        default="mock_provider",
                        help_text="The source of the KYC verification.",
                        max_length=100,
                    ),
                ),
                (
                    "mock_response",
                    models.JSONField(
                        blank=True,
                        help_text="The raw mock response from the KYC API.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when this record was created.",
                    ),
                ),
            ],
        ),
    ]
