# Generated by Django 5.2 on 2025-04-29 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockExperianReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bureau_score', models.IntegerField(help_text='The credit score of the user.', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(900)])),
                ('score_band', models.CharField(choices=[('poor', 'Poor (300-579)'), ('fair', 'Fair (580-669)'), ('good', 'Good (670-739)'), ('very_good', 'Very Good (740-799)'), ('excellent', 'Excellent (800-900)')], help_text='The band of the credit score.', max_length=100)),
                ('report_status', models.CharField(choices=[('mocked', 'Mocked'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', help_text='The status of the report.', max_length=50)),
                ('total_accounts', models.PositiveIntegerField(help_text='The total number of credit accounts.')),
                ('active_accounts', models.PositiveIntegerField(help_text='The number of active credit accounts.')),
                ('overdue_accounts', models.PositiveIntegerField(help_text='The number of overdue credit accounts.')),
                ('dpd_max', models.PositiveIntegerField(help_text='The maximum number of Days Past Due (DPD) for credit accounts.')),
                ('credit_utilization_pct', models.FloatField(help_text='The percentage of credit utilization.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('emi_to_income_ratio', models.FloatField(help_text='The ratio of EMI to income.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('tradelines', models.JSONField(blank=True, default=list, help_text='The tradelines in the credit report.', null=True)),
                ('enquiries', models.JSONField(blank=True, default=list, help_text='The enquiries in the credit report.', null=True)),
                ('mock_raw_report', models.JSONField(default=dict, help_text='The raw mock API response for the credit report.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this report was created.')),
            ],
            options={
                'verbose_name': 'Mock Experian Report',
                'verbose_name_plural': 'Mock Experian Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockKYCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(help_text='The PAN number of the user.', max_length=20, validators=[django.core.validators.MinLengthValidator(10)])),
                ('pan_holder_name', models.CharField(help_text='The name on the PAN card.', max_length=255)),
                ('pan_verified', models.BooleanField(default=False, help_text='Indicates whether the PAN is verified.')),
                ('aadhaar_last_4', models.CharField(help_text='The last 4 digits of the Aadhaar number.', max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('aadhaar_verified', models.BooleanField(default=False, help_text='Indicates whether the Aadhaar is verified.')),
                ('dob', models.DateField(help_text='The date of birth of the user.')),
                ('kyc_type', models.CharField(choices=[('full', 'Full KYC'), ('simplified', 'Simplified KYC')], default='simplified', help_text='The type of KYC (full or simplified).', max_length=50)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', help_text='The status of the KYC verification.', max_length=50)),
                ('verification_source', models.CharField(choices=[('mock_provider', 'Mock Provider'), ('real_provider', 'Real Provider')], default='mock_provider', help_text='The source of the KYC verification.', max_length=100)),
                ('mock_response', models.JSONField(blank=True, default=dict, help_text='The raw mock response from the KYC API.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was created.')),
            ],
            options={
                'verbose_name': 'Mock KYC Record',
                'verbose_name_plural': 'Mock KYC Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
