# Generated by Django 5.2 on 2025-04-29 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('loanapplications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexperianreport',
            name='loan_application',
            field=models.ForeignKey(help_text='The loan application associated with this mock Experian report.', on_delete=django.db.models.deletion.CASCADE, related_name='mock_experian', to='loanapplications.loanapplication'),
        ),
    ]
