# Generated by Django 5.1.4 on 2025-04-26 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mockexperianreport",
            name="user",
            field=models.ForeignKey(
                help_text="The user associated with this mock Experian report.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mockkycrecord",
            name="user",
            field=models.OneToOneField(
                help_text="The user associated with this mock KYC record.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mock_kyc",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
