# Generated by Django 5.1.4 on 2025-04-26 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mockexperianreport",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Mock Experian Report",
                "verbose_name_plural": "Mock Experian Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="mockkycrecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Mock KYC Record",
                "verbose_name_plural": "Mock KYC Records",
            },
        ),
        migrations.AlterField(
            model_name="mockexperianreport",
            name="active_accounts",
            field=models.PositiveIntegerField(
                help_text="The number of active credit accounts."
            ),
        ),
        migrations.AlterField(
            model_name="mockexperianreport",
            name="bureau_score",
            field=models.IntegerField(
                help_text="The credit score of the user.",
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(900),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mockexperianreport",
            name="credit_utilization_pct",
            field=models.FloatField(
                help_text="The percentage of credit utilization.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mockexperianreport",
            name="dpd_max",
            field=models.PositiveIntegerField(
                help_text="The maximum number of Days Past Due (DPD) for credit accounts."
            ),
        ),
        migrations.AlterField(
            model_name="mockexperianreport",
            name="emi_to_income_ratio",
            field=models.FloatField(
                help_text="The ratio of EMI to income.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mockexperianreport",
            name="overdue_accounts",
            field=models.PositiveIntegerField(
                help_text="The number of overdue credit accounts."
            ),
        ),
        migrations.AlterField(
            model_name="mockexperianreport",
            name="report_status",
            field=models.CharField(
                choices=[
                    ("mocked", "Mocked"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="processing",
                help_text="The status of the report.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mockexperianreport",
            name="score_band",
            field=models.CharField(
                choices=[
                    ("poor", "Poor (300-579)"),
                    ("fair", "Fair (580-669)"),
                    ("good", "Good (670-739)"),
                    ("very_good", "Very Good (740-799)"),
                    ("excellent", "Excellent (800-850)"),
                ],
                help_text="The band of the credit score.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="mockexperianreport",
            name="total_accounts",
            field=models.PositiveIntegerField(
                help_text="The total number of credit accounts."
            ),
        ),
        migrations.AlterField(
            model_name="mockexperianreport",
            name="user",
            field=models.ForeignKey(
                help_text="The user associated with this mock Experian report.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experian_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mockkycrecord",
            name="aadhaar_last_4",
            field=models.CharField(
                help_text="The last 4 digits of the Aadhaar number.",
                max_length=4,
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mockkycrecord",
            name="aadhaar_verified",
            field=models.BooleanField(
                default=False, help_text="Indicates whether the Aadhaar is verified."
            ),
        ),
        migrations.AlterField(
            model_name="mockkycrecord",
            name="kyc_type",
            field=models.CharField(
                choices=[("full", "Full KYC"), ("simplified", "Simplified KYC")],
                default="simplified",
                help_text="The type of KYC (full or simplified).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mockkycrecord",
            name="pan_number",
            field=models.CharField(
                help_text="The PAN number of the user.",
                max_length=20,
                validators=[django.core.validators.MinValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="mockkycrecord",
            name="pan_verified",
            field=models.BooleanField(
                default=False, help_text="Indicates whether the PAN is verified."
            ),
        ),
        migrations.AlterField(
            model_name="mockkycrecord",
            name="verification_source",
            field=models.CharField(
                choices=[
                    ("mock_provider", "Mock Provider"),
                    ("real_provider", "Real Provider"),
                ],
                default="mock_provider",
                help_text="The source of the KYC verification.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="mockkycrecord",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="The status of the KYC verification.",
                max_length=50,
            ),
        ),
    ]
