# Generated by Django 5.1.4 on 2025-04-26 11:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riskdashboards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelperformancelog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="risksnapshot",
            options={"ordering": ["-snapshot_date"]},
        ),
        migrations.AlterModelOptions(
            name="risktrend",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="modelperformancelog",
            name="accuracy",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="modelperformancelog",
            name="auc_score",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="modelperformancelog",
            name="model_version",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="modelperformancelog",
            name="precision",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="modelperformancelog",
            name="recall",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="modelperformancelog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="risksnapshot",
            name="approved_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="risksnapshot",
            name="avg_risk_score",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="risksnapshot",
            name="high_risk_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="risksnapshot",
            name="low_risk_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="risksnapshot",
            name="model_version",
            field=models.CharField(db_index=True, default="xgboost_v1", max_length=50),
        ),
        migrations.AlterField(
            model_name="risksnapshot",
            name="rejected_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="risksnapshot",
            name="snapshot_date",
            field=models.DateField(
                db_index=True, default=datetime.date.today, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="risksnapshot",
            name="total_applications",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="risksnapshot",
            name="under_review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="risktrend",
            name="approval_rate",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="risktrend",
            name="avg_score",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="risktrend",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="risktrend",
            name="model_version",
            field=models.CharField(db_index=True, default="xgboost_v1", max_length=50),
        ),
        migrations.AlterField(
            model_name="risktrend",
            name="rejection_rate",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="modelperformancelog",
            index=models.Index(
                fields=["timestamp", "model_version"],
                name="riskdashboa_timesta_c3ecc9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="risksnapshot",
            index=models.Index(
                fields=["snapshot_date", "model_version"],
                name="riskdashboa_snapsho_dc30a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="risktrend",
            index=models.Index(
                fields=["date", "model_version"], name="riskdashboa_date_42b8c0_idx"
            ),
        ),
    ]
