# Generated by Django 5.2 on 2025-04-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('overridden', 'Overridden'), ('modified', 'Modified')], help_text='The type of action performed.', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the action was performed.')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context for the action.')),
            ],
            options={
                'verbose_name': 'Compliance Audit Trail',
                'verbose_name_plural': 'Compliance Audit Trails',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('kyc', 'KYC Verification'), ('aml', 'Anti-Money Laundering'), ('credit_policy', 'Credit Policy Compliance'), ('fraud', 'Fraud Detection'), ('other', 'Other')], help_text='The type of compliance check being performed.', max_length=50)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('flagged', 'Flagged'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', help_text='The status of the compliance check.', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the compliance review.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the compliance check was created.')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='The timestamp when the compliance check was reviewed.', null=True)),
                ('is_compliant', models.BooleanField(default=False, help_text='Indicates whether the compliance check passed all requirements.')),
            ],
            options={
                'verbose_name': 'Compliance Check',
                'verbose_name_plural': 'Compliance Checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
