# Generated by Django 5.1.4 on 2025-04-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComplianceAuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="The action performed, e.g., 'Approved', 'Rejected', 'Overridden'.",
                        max_length=255,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the action was performed.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or context for the action.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("kyc", "KYC Verification"),
                            ("aml", "Anti-Money Laundering"),
                            ("credit_policy", "Credit Policy Compliance"),
                            ("fraud", "Fraud Detection"),
                            ("other", "Other"),
                        ],
                        help_text="The type of compliance check being performed.",
                        max_length=50,
                    ),
                ),
                (
                    "is_compliant",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("flagged", "Flagged"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        help_text="The status of the compliance check.",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or observations about the compliance check.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the compliance check was created.",
                    ),
                ),
                (
                    "checked_on",
                    models.DateTimeField(
                        blank=True,
                        help_text="The timestamp when the compliance check was reviewed.",
                        null=True,
                    ),
                ),
                (
                    "check_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or context for the action.",
                    ),
                ),
            ],
        ),
    ]
