# Generated by Django 5.1.4 on 2025-04-26 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliances", "0001_initial"),
        ("loanapplications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceaudittrail",
            name="actor",
            field=models.ForeignKey(
                help_text="The user who performed the action.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceaudittrail",
            name="loan_application",
            field=models.ForeignKey(
                help_text="The loan application related to this action.",
                on_delete=django.db.models.deletion.CASCADE,
                to="loanapplications.loanapplication",
            ),
        ),
        migrations.AddField(
            model_name="compliancecheck",
            name="loan_application",
            field=models.ForeignKey(
                help_text="The loan application being checked for compliance.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_checks",
                to="loanapplications.loanapplication",
            ),
        ),
        migrations.AddField(
            model_name="compliancecheck",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who reviewed this compliance check.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
