# Generated by Django 5.2 on 2025-04-29 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliances', '0001_initial'),
        ('loanapplications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceaudittrail',
            name='actor',
            field=models.ForeignKey(help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceaudittrail',
            name='loan_application',
            field=models.ForeignKey(help_text='The loan application related to this action.', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_audit_trail', to='loanapplications.loanapplication'),
        ),
        migrations.AddField(
            model_name='compliancecheck',
            name='loan_application',
            field=models.ForeignKey(help_text='The loan application being checked for compliance.', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='loanapplications.loanapplication'),
        ),
        migrations.AddField(
            model_name='compliancecheck',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='The user who reviewed this compliance check.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancecheck',
            name='user',
            field=models.ForeignKey(default=None, help_text='The user who initiated this compliance check.', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_checks', to=settings.AUTH_USER_MODEL),
        ),
    ]
