# Generated by Django 5.1.4 on 2025-04-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditScoreRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="xgboost_v1",
                        help_text="The name or version of the ML model used for scoring.",
                        max_length=100,
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        help_text="The calculated risk score for this loan application."
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("manual_review", "Manual Review"),
                        ],
                        help_text="The decision made by the model for this loan application.",
                        max_length=20,
                    ),
                ),
                (
                    "scoring_inputs",
                    models.JSONField(
                        help_text="Input features used by the model for scoring."
                    ),
                ),
                (
                    "scoring_output",
                    models.JSONField(
                        blank=True,
                        help_text="Optional: Model outputs like SHAP values or feature importance.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the credit score record was created.",
                    ),
                ),
                (
                    "credit_utilization_pct",
                    models.FloatField(
                        blank=True,
                        help_text="The credit utilization percentage of the user at the time of scoring.",
                        null=True,
                    ),
                ),
                (
                    "dpd_max",
                    models.IntegerField(
                        blank=True,
                        help_text="The maximum number of days past due for the user in their credit history.",
                        null=True,
                    ),
                ),
                (
                    "emi_to_income_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="The ratio of the user's equated monthly installment (EMI) to their monthly income.",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
