# Generated by Django 5.2 on 2025-04-29 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='xgboost_v1', help_text='The name or version of the ML model used for scoring.', max_length=100)),
                ('risk_score', models.FloatField(help_text='The calculated risk score for this loan application (between 0 and 1).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('manual_review', 'Manual Review')], default='manual_review', help_text='The decision made by the model for this loan application.', max_length=20)),
                ('scoring_inputs', models.JSONField(default=dict, help_text='Input features used by the model for scoring.')),
                ('scoring_output', models.JSONField(blank=True, default=dict, help_text='Optional: Model outputs like SHAP values or feature importance.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the credit score record was created.')),
                ('credit_utilization_pct', models.FloatField(blank=True, help_text='The credit utilization percentage of the user at the time of scoring (0-100%).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('dpd_max', models.IntegerField(blank=True, help_text='The maximum number of days past due for the user in their credit history.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('emi_to_income_ratio', models.FloatField(blank=True, help_text="The ratio of the user's equated monthly installment (EMI) to their monthly income (between 0 and 1).", null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
