# Generated by Django 5.2 on 2025-04-29 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditscorings', '0001_initial'),
        ('loanapplications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscorerecord',
            name='loan_application',
            field=models.OneToOneField(help_text='The loan application associated with this credit score record.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_scoring_record', to='loanapplications.loanapplication'),
        ),
    ]
