# Generated by Django 5.1.4 on 2025-04-26 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creditscorings", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="creditscorerecord",
            name="user",
            field=models.ForeignKey(
                help_text="The user associated with this credit score record.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_scores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
