# Generated by Django 5.1.4 on 2025-04-26 11:17

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditscorings", "0003_initial"),
        ("loanapplications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditscorerecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="creditscorerecord",
            name="credit_utilization_pct",
            field=models.FloatField(
                blank=True,
                help_text="The credit utilization percentage of the user at the time of scoring (0-100%).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="creditscorerecord",
            name="decision",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("manual_review", "Manual Review"),
                ],
                default="manual_review",
                help_text="The decision made by the model for this loan application.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="creditscorerecord",
            name="dpd_max",
            field=models.IntegerField(
                blank=True,
                help_text="The maximum number of days past due for the user in their credit history.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="creditscorerecord",
            name="emi_to_income_ratio",
            field=models.FloatField(
                blank=True,
                help_text="The ratio of the user's equated monthly installment (EMI) to their monthly income (between 0 and 1).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="creditscorerecord",
            name="risk_score",
            field=models.FloatField(
                help_text="The calculated risk score for this loan application (between 0 and 1).",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="creditscorerecord",
            name="scoring_inputs",
            field=models.JSONField(
                default=dict, help_text="Input features used by the model for scoring."
            ),
        ),
        migrations.AlterField(
            model_name="creditscorerecord",
            name="scoring_output",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional: Model outputs like SHAP values or feature importance.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="creditscorerecord",
            index=models.Index(
                fields=["user", "created_at"], name="creditscori_user_id_c743b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditscorerecord",
            index=models.Index(
                fields=["loan_application"], name="creditscori_loan_ap_981062_idx"
            ),
        ),
    ]
