# Generated by Django 5.2 on 2025-04-29 07:25

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Enter a 10-digit phone number without any spaces or special characters', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, help_text='Annual income in local currency', max_digits=12, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired')], max_length=100, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300, 'Credit score must be at least 300.'), django.core.validators.MaxValueValidator(900, 'Credit score cannot exceed 900.')])),
                ('credit_history_fetched', models.BooleanField(default=False)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('kyc_verified_on', models.DateTimeField(blank=True, null=True)),
                ('govt_id_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('national_id', 'National ID')], max_length=100, null=True)),
                ('govt_id_number', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinValueValidator(6, 'Government ID number must be at least 6 characters.'), django.core.validators.MaxValueValidator(100, 'Government ID number cannot exceed 100 characters.')])),
                ('id_proof', models.FileField(blank=True, help_text='Upload government issued photo ID', null=True, upload_to=users.models.user_document_upload_path)),
                ('address_proof', models.FileField(blank=True, help_text='Upload proof of current residential address', null=True, upload_to=users.models.user_document_upload_path)),
                ('income_proof', models.FileField(blank=True, help_text='Upload latest salary slip or tax returns', null=True, upload_to=users.models.user_document_upload_path)),
                ('experian_customer_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('last_experian_sync', models.DateTimeField(blank=True, null=True)),
                ('experian_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
