# Generated by Django 5.1.4 on 2025-05-01 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="govt_id_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        6, "Government ID number must be at least 6 characters long."
                    ),
                    django.core.validators.MaxLengthValidator(
                        100, "Government ID number cannot exceed 100 characters."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="govt_id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Passport", "Passport"),
                    ("driving_license", "Driving License"),
                    ("national_id", "National ID"),
                    ("SSN", "SSN"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
