# Generated by Django 5.1.4 on 2025-04-26 10:35

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address_proof",
            field=models.FileField(
                blank=True,
                help_text="Upload proof of current residential address",
                null=True,
                upload_to=users.models.user_document_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="annual_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Annual income in local currency",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="credit_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(300),
                    django.core.validators.MaxLengthValidator(900),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employed", "Employed"),
                    ("self_employed", "Self Employed"),
                    ("unemployed", "Unemployed"),
                    ("retired", "Retired"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="govt_id_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        6, "Government ID number must be at least 6 characters."
                    ),
                    django.core.validators.MaxLengthValidator(
                        100, "Government ID number cannot exceed 100 characters."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="govt_id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("passport", "Passport"),
                    ("driving_license", "Driving License"),
                    ("national_id", "National ID"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id_proof",
            field=models.FileField(
                blank=True,
                help_text="Upload government issued photo ID",
                null=True,
                upload_to=users.models.user_document_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="income_proof",
            field=models.FileField(
                blank=True,
                help_text="Upload latest salary slip or tax returns",
                null=True,
                upload_to=users.models.user_document_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter 10 digit phone number without any spaces or special characters",
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
