# Generated by Django 5.2 on 2025-04-29 07:25

import django.core.validators
import loanapplications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, default=0.01, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('purpose', models.CharField(max_length=255)),
                ('term_months', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.01, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('existing_loans', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('ai_decision', models.CharField(blank=True, choices=[('approve', 'Approve'), ('reject', 'Reject'), ('manual_review', 'Manual Review')], max_length=20, null=True)),
                ('ml_scoring_output', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_score_records', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(300)])),
            ],
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('salary_slip', 'Salary Slip'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof')], max_length=100)),
                ('file', models.FileField(upload_to=loanapplications.models.loan_doc_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
