# Generated by Django 5.2 on 2025-04-29 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loanapplications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loanapplications.loanapplication'),
        ),
        migrations.AlterUniqueTogether(
            name='loandocument',
            unique_together={('loan', 'document_type')},
        ),
    ]
