# Generated by Django 5.1.4 on 2025-04-26 11:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loanapplications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapplication",
            name="amount_requested",
            field=models.DecimalField(
                decimal_places=2,
                default=0.01,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="credit_score_records",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(300)],
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="monthly_income",
            field=models.DecimalField(
                decimal_places=2,
                default=0.01,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="term_months",
            field=models.PositiveIntegerField(
                default=12, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loandocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("bank_statement", "Bank Statement"),
                    ("salary_slip", "Salary Slip"),
                    ("id_proof", "ID Proof"),
                    ("address_proof", "Address Proof"),
                ],
                max_length=100,
            ),
        ),
    ]
